### ISSUE TITLE
Can't start server

### ISSUE THREAD

**Issue by omargon** [auth0/nodejs-jwt-authentication-sample#17]
Hi not sure if I did understood the instructions but after cloning the repo, running `npm install` and then `node server.js` I get the following error:

```
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::3001
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at Server._listen2 (net.js:1234:14)
    at listen (net.js:1270:10)
    at Server.listen (net.js:1366:5)
    at Object.<anonymous> (/Users/omar/Development/nodejs-jwt-authentication-sample/server.js:40:24)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
```

Any help will be appreciated.

**Comment by omargon** [comment]
I found the issue. I was running another server already. Closing the issue.
